train_lines:  # Enter the train line numbers below
  - ""
  - ""

train_stations:  # Enter the train station names below
  - ""
  - ""

output_file_name: ""  # Enter the output text file name here
download_dir_name: ""  # Enter the download directory name here
download_latency: ""  # Enter a delay value here after each file is downloaded